### ISSUE TITLE
Review for ReactGroupProject Kanban board

### ISSUE THREAD

**Issue by rex-9** [rex-9/XRocket#25]
The link to our React Kanban Board - https://github.com/users/rex-9/projects/2 

There are 2 people on the team: 
- @rex-9 will do Missions and
- @bahoz-ali will do Rockets

**Comment by BenMukebo** [comment]
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @rex-9, @bahoz-ali**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has:  
  - Link to their GitHub project 👍🏻 
  - Information about the number of people in their group 👏🏻  
- All cards are assigned to team members 🥇 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
